# Generated by Django 4.1.4 on 2022-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A field to get name of the users', max_length=30)),
                ('phone_number', models.CharField(help_text='A field to get the phone number of the users', max_length=30)),
                ('adhar_number', models.CharField(help_text='A field to get the adhar number of the users', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['phone_number']},
        ),
    ]
