# Generated by Django 4.1.4 on 2022-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_image_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
