# Generated by Django 4.1.4 on 2022-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
