# Generated by Django 4.1.4 on 2022-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
