# Generated by Django 4.1.4 on 2022-12-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_booking_guide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Profile',
        ),
    ]
