# Generated by Django 4.1.4 on 2022-12-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_profile_options_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
