# Generated by Django 4.1.4 on 2022-12-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
