# Generated by Django 4.1.4 on 2022-12-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_image_state_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='state',
        ),
        migrations.AddField(
            model_name='image',
            name='pitche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
    ]
