# Generated by Django 4.1.4 on 2022-12-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_pitche_image_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.image'),
        ),
    ]
