# Generated by Django 4.1.4 on 2022-12-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_hotels_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
