# Generated by Django 4.1.4 on 2022-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_delete_contact_delete_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='A field to get the phone number of the users', max_length=30, null=True)),
            ],
            options={
                'ordering': ['mobile'],
            },
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='destination',
        ),
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.CharField(blank=True, default='no state', max_length=40, null=True),
        ),
    ]
