# Generated by Django 4.1.4 on 2022-12-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_booking_delete_bookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
